### ISSUE TITLE
GUI Not appearing

### ISSUE THREAD

**Issue by MSIvortex** [Four-DJ/RoundWare#1]
Hello first wanted to say what an awesome thing you made here. It used to work really well and enjoyed messing with the infinite ammo and fly options. But one day the GUI stopped appearing in the top left thus not allowing me to use this hack. Do you know why this is happening? If so is there a way to fix it? I followed the tutorial video and did exactly what it said and still no luck. Any help will be appreciated thanks.

**Comment by Four-DJ** [comment]
I just tested the mod and everything still works, are there any errors you get in the console?

**Comment by MSIvortex** [comment]
Nope I get no errors in the console. I’m gonna try reinstalling the game maybe I messed up the game some how 🤷‍♂️ Will let you know if the mod works after doing this.

**Comment by MSIvortex** [comment]
After reinstalling the game the mod now works! The GUI disappears sometimes.  But all in all the GUI is now appearing again so it looks like I just had to reinstall the game a second time for it to work.
